### ISSUE TITLE
Peer Dependencies prevent install with @react-pdf/renderer v2.0.0

### ISSUE THREAD

**Issue by e-compton** [react-pdf/styled-components#12]
Trying to install this module with @react-pdf/renderer v2.0.0 causes this error:
```
▶ npm i @react-pdf/styled-components
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mach-one-members-api@1.0.0
npm ERR! Found: @react-pdf/renderer@2.0.0
npm ERR! node_modules/@react-pdf/renderer
npm ERR!   @react-pdf/renderer@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @react-pdf/renderer@"^1.0.0" from @react-pdf/styled-components@1.4.0
npm ERR! node_modules/@react-pdf/styled-components
npm ERR!   @react-pdf/styled-components@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Workaround is to install with legacy peer deps option:
```
npm i @react-pdf/styled-components --legacy-peer-deps
```

But ideally this package would have its peer-dependencies updated so that it can work with the new version of @react-pdf/renderer without having to add the option to all the install scripts.

**Comment by diegomura** [comment]
Please check #1062. Thanks!

**Comment by e-compton** [comment]
#1062 in @react-pdf/renderer is about peer dependencies with React. This error is between @react-pdf/renderer and @react-pdf/styled-components.
```
npm ERR! Could not resolve dependency:
npm ERR! peer @react-pdf/renderer@"^1.0.0" from @react-pdf/styled-components@1.4.0
```

Does this project support @react-pdf/renderer 2.0.0? 
```
// package.json
  "peerDependencies": {
    "@react-pdf/renderer": "^1.0.0"
  },
```

**Comment by diegomura** [comment]
I recommend stop using this `styled-components` plugin, for many reasons. First, it adds a log of bundle size for your app, and also the new styled-component version internals changed a lot and it's not longer possible to provide support. Sorry about that
