### ISSUE TITLE
Error render styled component web version

### ISSUE THREAD

**Issue by llmdev** [react-pdf/styled-components#6]
Uncaught TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported.

**Comment by diegomura** [comment]
It’s hard to get what’s going on based on your short description. Please provide more info

**Comment by llmdev** [comment]
I solved thx

**Comment by luskin** [comment]
@llmdev can you please provide your solution? We are stuck on this error, thanks!

**Comment by luskin** [comment]
@llmdev would you please mind sharing your solution? We are still stuck with this problem, please help out the community!

**Comment by luskin** [comment]
@diegomura do you have any further advice on how to resolve this issue?
